export const schools = [
  {
    id: 1,
    name: "The Global Edge School",
    location: "Kukatpally, Hyderabad",
    fee: "₹1.2L",
    rating: 4.8,
    badge: "TOP MATCH",
    score: 98,
    shade: "bg-blue-50",
    boards: ["CBSE"],
    tags: ["STEM", "Sports", "Digital Campus"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 2,
    name: "Oakridge International",
    location: "Gachibowli, Hyderabad",
    fee: "₹4.5L",
    rating: 4.9,
    badge: "PREMIUM",
    score: 95,
    shade: "bg-emerald-50",
    boards: ["IB", "CBSE"],
    tags: ["International", "Infrastructure", "Arts"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 3,
    name: "Delhi Public School",
    location: "Nacharam, Hyderabad",
    fee: "₹1.8L",
    rating: 4.7,
    badge: "LEGACY",
    score: 92,
    shade: "bg-amber-50",
    boards: ["CBSE"],
    tags: ["Academics", "Discipline", "Alumni"],
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 4,
    name: "Silver Oaks International",
    location: "Miyapur, Hyderabad",
    fee: "₹2.2L",
    rating: 4.6,
    badge: "BALANCED",
    score: 89,
    shade: "bg-rose-50",
    boards: ["IB", "CBSE"],
    tags: ["Inquiry Based", "Value Driven"],
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 5,
    name: "Chirec International",
    location: "Kondapur, Hyderabad",
    fee: "₹5.5L",
    rating: 4.9,
    badge: "ELITE",
    score: 97,
    shade: "bg-indigo-50",
    boards: ["IB", "ICSE", "CBSE"],
    tags: ["Holistic", "Sports Academy"],
  },
  {
    id: 6,
    name: "Glendale Academy",
    location: "Golconda, Hyderabad",
    fee: "₹2.8L",
    rating: 4.7,
    badge: "NATURE",
    score: 91,
    shade: "bg-teal-50",
    boards: ["CBSE", "IB"],
    tags: ["Experiential", "Campus"],
  },
  {
    id: 7,
    name: "Phoenix Greens School",
    location: "Kokapet, Hyderabad",
    fee: "₹2.1L",
    rating: 4.5,
    badge: "GROWING",
    score: 88,
    shade: "bg-orange-50",
    boards: ["CBSE"],
    tags: ["Personalized", "Tech-Ready"],
  },
  {
    id: 8,
    name: "Rockwell International",
    location: "Jubilee Hills, Hyderabad",
    fee: "₹3.2L",
    rating: 4.6,
    badge: "INNOVATIVE",
    score: 90,
    shade: "bg-violet-50",
    boards: ["CBSE", "IB"],
    tags: ["Critical Thinking", "Arts"],
  }
];

export const teachers = [
  { id: 1, name: 'Anjali Sharma', subject: 'Mathematics', grade: 'Grade 6-10', exp: 8, rating: 4.9, fee: 600, city: 'Hyderabad', locality: 'Punjagutta', mode: 'Both', bio: 'Experienced mathematics tutor with a passion for making complex concepts simple for students.', education: 'M.Sc in Mathematics, Osmania University' },
  { id: 2, name: 'Rahul Verma', subject: 'Physics', grade: 'Grade 9-12', exp: 12, rating: 4.8, fee: 900, city: 'Bengaluru', locality: 'Indiranagar', mode: 'Online', bio: 'Specializing in competitive exam prep (JEE/NEET) with over 12 years of teaching experience.', education: 'B.Tech from IIT Madras' },
  { id: 3, name: 'Priya Nair', subject: 'English', grade: 'Grade 1-8', exp: 6, rating: 4.9, fee: 500, city: 'Chennai', locality: 'Adyar', mode: 'Offline', bio: 'Focusing on communication skills and literature analysis for primary and middle school students.', education: 'M.A in English Literature' },
  { id: 4, name: 'Suresh Kumar', subject: 'Chemistry', grade: 'Grade 11-12', exp: 15, rating: 4.9, fee: 1200, city: 'Delhi NCR', locality: 'Gurugram', mode: 'Both', bio: 'Chemistry expert with 15+ years of teaching. Helping students master organic and inorganic chemistry.', education: 'Ph.D in Chemistry' },
  { id: 5, name: 'Neha Iyer', subject: 'Biology', grade: 'Grade 9-12', exp: 10, rating: 4.8, fee: 800, city: 'Mumbai', locality: 'Andheri', mode: 'Online', bio: 'Biology enthusiast focusing on conceptual clarity and exam-oriented preparation.', education: 'M.Sc in Life Sciences' },
  { id: 6, name: 'Arjun Reddy', subject: 'Mathematics', grade: 'Grade 11-12', exp: 9, rating: 4.7, fee: 1000, city: 'Hyderabad', locality: 'Madhapur', mode: 'Both', bio: 'Passionate math teacher specializing in high school calculus and algebra.', education: 'B.Ed, University of Hyderabad' },
  { id: 7, name: 'Kavya Menon', subject: 'Hindi', grade: 'Grade 1-10', exp: 7, rating: 4.8, fee: 400, city: 'Pune', locality: 'Kothrud', mode: 'Offline', bio: 'Native Hindi speaker with a focus on grammar and conversational skills.', education: 'B.A in Hindi Literature' },
  { id: 8, name: 'Rajat Kapoor', subject: 'Computer Science', grade: 'Grade 8-12', exp: 11, rating: 4.9, fee: 1100, city: 'Bengaluru', locality: 'Koramangala', mode: 'Online', bio: 'Software engineer turned teacher. Specializing in Python, Java, and Web Development.', education: 'M.Tech in CS' },
  { id: 9, name: 'Sneha Patil', subject: 'English', grade: 'Grade 9-12', exp: 8, rating: 4.8, fee: 700, city: 'Pune', locality: 'Baner', mode: 'Both', bio: 'Focusing on creative writing and advanced grammar for high schoolers.', education: 'M.A in English' },
  { id: 10, name: 'Vikram Joshi', subject: 'Physics', grade: 'Grade 11-12', exp: 14, rating: 4.9, fee: 1300, city: 'Mumbai', locality: 'Bandra', mode: 'Both', bio: 'Physics veteran with a deep understanding of mechanics and electromagnetism.', education: 'M.Sc Physics' },
  { id: 11, name: 'Deepa Rao', subject: 'Biology', grade: 'Grade 6-10', exp: 5, rating: 4.7, fee: 550, city: 'Chennai', locality: 'Anna Nagar', mode: 'Online', bio: 'Young and energetic biology teacher focusing on visual learning techniques.', education: 'B.Sc in Zoology' },
  { id: 12, name: 'Amit Shah', subject: 'Social Studies', grade: 'Grade 6-10', exp: 9, rating: 4.8, fee: 600, city: 'Delhi NCR', locality: 'Noida', mode: 'Offline', bio: 'History and Geography expert with a knack for storytelling.', education: 'M.A in History' },
];

export const localities = {
  'Hyderabad': ['All', 'Punjagutta', 'Madhapur', 'Kukatpally', 'Banjara Hills', 'Gachibowli', 'Secunderabad'],
  'Bengaluru': ['All', 'Indiranagar', 'Koramangala', 'HSR Layout', 'Whitefield', 'Jayanagar'],
  'Mumbai': ['All', 'Andheri', 'Bandra', 'Juhu', 'Colaba', 'Borivali'],
  'Delhi NCR': ['All', 'Gurugram', 'Noida', 'Saket', 'Dwarka', 'Rohini'],
  'Chennai': ['All', 'Adyar', 'Anna Nagar', 'Velachery', 'T. Nagar'],
  'Pune': ['All', 'Kothrud', 'Baner', 'Viman Nagar', 'Hinjewadi'],
};
